name: Clasificador de Etapa de Vida

on:
  workflow_dispatch:

jobs:
  clasificar-etapa:
    runs-on: ubuntu-latest
    steps:
      - name: Clasificar según edad
        run: |
          edad=24

          lim_ninez=$(expr $LIM_NINEZ + 0)
          lim_adolescencia=$(expr $LIM_ADOLESCENCIA + 0)
          lim_adulto_joven=$(expr $LIM_ADULTO_JOVEN + 0)
          lim_adulto=$(expr $LIM_ADULTO + 0)

          if [ "$edad" -le "$lim_ninez" ]; then
            etapa="Niñez"
          elif [ "$edad" -le "$lim_adolescencia" ]; then
            etapa="Adolescencia"
          elif [ "$edad" -le "$lim_adulto_joven" ]; then
            etapa="Adulto Joven"
          elif [ "$edad" -le "$lim_adulto" ]; then
            etapa="Adulto"
          elif [ "$edad" -ge $((lim_adulto + 1)) ]; then
            etapa="Tercera Edad"
          else
            etapa="No clasificada"
          fi

          echo "Edad: $edad años"
          echo "Etapa de vida: $etapa"