name: Clasificador de Etapa de Vida

on:
  workflow_dispatch:
    inputs:
      dia:
        description: 'Día de nacimiento'
        required: true
      mes:
        description: 'Mes de nacimiento'
        required: true
      anio:
        description: 'Año de nacimiento'
        required: true

jobs:
  calcular-edad:
    runs-on: ubuntu-latest
    outputs:
      edad: ${{ steps.calcular.outputs.edad }}
    steps:
      - name: Calcular edad
        id: calcular
        run: |
          dia="${{ github.event.inputs.dia }}"
          mes="${{ github.event.inputs.mes }}"
          anio="${{ github.event.inputs.anio }}"

          nacimiento="$anio-$mes-$dia"
          hoy=$(date +%Y-%m-%d)

          edad=$(($(date -d "$hoy" +%s) - $(date -d "$nacimiento" +%s)))
          edad=$((edad / 31556926))  # segundos en un año promedio

          echo "Edad calculada: $edad"
          echo "edad=$edad" >> $GITHUB_OUTPUT

  clasificar-etapa:
    needs: calcular-edad
    runs-on: ubuntu-latest
    steps:
      - name: Clasificar según edad
        run: |
          edad=${{ needs.calcular-edad.outputs.edad }}

          LIM_NINEZ=${{ vars.LIM_NINEZ }}
          LIM_ADOLESCENCIA=${{ vars.LIM_ADOLESCENCIA }}
          LIM_ADULTO_JOVEN=${{ vars.LIM_ADULTO_JOVEN }}
          LIM_ADULTO=${{ vars.LIM_ADULTO }}

          if [ "$edad" -le "$LIM_NINEZ" ]; then
            etapa="Niñez"
          elif [ "$edad" -le "$LIM_ADOLESCENCIA" ]; then
            etapa="Adolescencia"
          elif [ "$edad" -le "$LIM_ADULTO_JOVEN" ]; then
            etapa="Adulto Joven"
          elif [ "$edad" -le "$LIM_ADULTO" ]; then
            etapa="Adulto"
          else
            etapa="Tercera Edad"
          fi

          echo "Edad: $edad años"
          echo "Etapa de vida: $etapa"
